files:
  - source: /Resources/Private/Language/
    ignore:
      - /Resources/Private/Language/de.*
      - /Resources/Private/Language/fr.*
      - /Resources/Private/Language/uk.*
    translation: /%original_path%/%two_letters_code%.%original_file_name%
